# Generated by Django 4.0.2 on 2022-03-11 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_business_name_loan_amount_loan_borrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='principle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
