# Generated by Django 4.0.2 on 2022-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='mpesa_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResponseCode', models.CharField(max_length=50)),
                ('ResponseDescription', models.CharField(max_length=50)),
                ('CustomerMessage', models.CharField(max_length=50)),
            ],
        ),
    ]
