# Generated by Django 4.0.2 on 2022-03-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0003_mpesa_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesa_response',
            name='response_data',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
